### ISSUE TITLE
Error with stomp.py==6.1.1

### ISSUE THREAD

**Issue by leandrovaladao** [juntossomosmais/django-stomp#38]
When update my stomp.py to version 6.1.1 I getting an error in on_message() saying that "body" is not a valid parameter for this function. To solve now I just downgraded my stomp.py to 6.1.0 and it works fine.

**Comment by fabiohk** [comment]
Thanks for the notice @leandrovaladao! Although the `6.1.0` is working to you, the [code with that tag](https://github.com/jasonrbriggs/stomp.py/blob/a2e0fb449ec537cdfcde06c9797ced3c89d2d365/stomp/listener.py#L102) can possible break our version, so we're releasing a version that fixes the version in [`6.0.0`](https://github.com/jasonrbriggs/stomp.py/blob/v6.0.0/stomp/listener.py#L103), which seems safer to assume that it won't break.

**Comment by fabiohk** [comment]
#44 updates to `stomp.py` version `~=7.0`
